### ISSUE TITLE
Build for openssl 1.1*

### ISSUE THREAD

**Issue by dhirschfeld** [conda-forge/thrift-cpp-feedstock#24]
As discussed on [gitter](https://gitter.im/conda-forge/conda-forge.github.io?at=5c614751604f233ab6edff29) `thrift-cpp` is currently only built against openssl `1.0.2p` whereas some newer libraries (e.g. `qt=5.9.7`) require `openssl=1.1*`

Since the recipe doesn't actually pin `openssl`:
https://github.com/conda-forge/thrift-cpp-feedstock/blob/c6c1d84ad21f58291ebcccb090ffe8f75b973dbc/recipe/meta.yaml#L40-L48

I'm not how to get `conda-forge` to build against the newer `openssl`

**Comment by xhochy** [comment]
This depends on `conda-forge-pinning` to be updated to a newer OpenSSL version.

**Comment by dhirschfeld** [comment]
I wait for the pinnings to be updated then...
