### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by jseabold** [conda-forge/thrift-cpp-feedstock#6]
Whenever one is available, will need a newer version to generate Python 3 compatible code AFAICT.

**Comment by jakirkham** [comment]
So, this is just the C++ portion, @jseabold. Are you thinking of [`thriftpy`](https://github.com/conda-forge/thriftpy-feedstock/)? If so, that appears to have Python 3 support. Is there something I'm missing here?

**Comment by jseabold** [comment]
Yep, I just saw that you weren't building the python code when I looked at the recipe. [This](https://pypi.python.org/pypi/thrift) must have gotten pulled in as a dependency somewhere else. Sorry for the noise.

**Comment by jseabold** [comment]
Ah, but the code generator is still going to generate Python code right, regardless if the language bindings are built?

**Comment by jseabold** [comment]
Though I guess that code isn't very useful without the language bindings? Sorry just getting my head around things here.

**Comment by wesm** [comment]
I created this feedstock for building C++ libraries that rely on the Thrift compiler for generating C++ bindings and that need to link (dynamically or statically) to libthrift. We can definitely add support for more languages to the thrift compiler if they are not here
